fix already borrowed error
Crash message:
  panicked at 'already borrowed: BorrowMutError', radiance\radiance\src\scene\entity.rs:73:33

The @components will borrow_mut() during iterating under borrow(), which
causes the crash.  Clone it before iterating to fix this crash.

Fixes: 34684ef ("Improve scene perf")
Signed-off-by: ryan <mr.iridescent.rsy@hotmail.com>